#!/usr/bin/env php
<?php

use Jamesrezo\TodoList\EisenhowerMethod\Decision;

require_once __DIR__ . '/../vendor/autoload.php';

$decision = new Decision;

$i = 0;
while ($decision->condition()) {
    if ($i == 0) {
        dump($decision->askQuestion());
        $decision->registerAnswer(true);
        dump('>> yes...');
    }

    if ($i == 1) {
        dump($decision->askQuestion());
        $decision->registerAnswer(false);
        dump('>> no...');
    }

    if ($i == 2) {
        dump($decision->askQuestion());
        $decision->registerAnswer((new DateTimeImmutable())->add(new DateInterval('P7D')));
        dump('>> in seven(7) days...');
    }
    $i++;
}

dump($decision->deliver());
